### ISSUE TITLE
Tooltip not working on VegaLite 

### ISSUE THREAD

**Issue by palaumarc** [vega/react-vega#178]
I am trying to add a tooltip to a VegaLite graph as stated in the documentation but it seems it is not working properly as it does not appear.

You can find an example code [in this Sandbox](https://codesandbox.io/s/serverless-firefly-qzup2?file=/src/App.js).

I would expect that the tooltip appears when hovering over the graph bars. I am trying to use `vega-tooltip`.

Maybe related to #48 and #70 ?

**Comment by jeppe-style** [comment]
I'm new to `react-vega`, however, if you put the hover in the spec itself it works
```
...
mark: { type: 'bar', tooltip: true },
...
```

**Comment by palaumarc** [comment]
Good catch! 

It seems I totally misunderstood the README 😞 

Thanks!
