### ISSUE TITLE
Width: "container" does not work properly

### ISSUE THREAD

**Issue by longlin58** [vega/react-vega#234]
when the width is set to container, adjusting the CSS for the div does not affect the width of the chart at all, and when interacting with the browser by resizing it only increases the width of the chart continuously. 
I'm not sure if this is a bug or if I'm doing something wrong, I have placed the vega-lite spec under a div tag and setting the width of it to 100%.

**Comment by domoritz** [comment]
Are you using container sizing in the Vega-Lite spec?

**Comment by longlin58** [comment]
```
import {createClassFromLiteSpec} from 'react-vega-lite';

export default createClassFromLiteSpec('StringencyChart', {
  "title": {
    "text": "government stringency",
    "align": "center",
    "fontSize": 20,
    "orient": "top",
    "anchor": "middle"
  },
  "width": "container",
  "autosize": {"type": "fit-x", "contains": "padding"},
  "height": 350,
  "transform": [
    {
      "filter": "datum.stringency > 0"
    }
  ],
  "mark": "line",
  "encoding": {
    "x": {
	  "timeUnit": "utcmonthdate",
      "field": "date",
      "type": "temporal"
    },
    "y": {
      "field": "stringency",
      "type": "quantitative"
    }
  }
});

```
this is my vega lite file, and that my js file for loading the graph

`import React from 'react';
import StringencyChart from '../vega/vega_stringency';
import {data_stringency} from '../../data/data-graphs';
import {Handler} from 'vega-tooltip';
import "./stringency.css";

function LoadStringency() {
    return <div className="card col-lg">
        <div className="card-body red">
            <StringencyChart 
				data={data_stringency} 
				className='showContainer'
			/>
        </div>
    </div>
}

export default LoadStringency;`

**Comment by domoritz** [comment]
Where are you setting the width?

Does https://github.com/vega/vega-embed/pull/490 solve your issue?

**Comment by longlin58** [comment]
```
.card-body {
  width: 100%;
  display: flex;
  align-items: center;
  justify-content: center;
}
```
I have set the width to 100% in the CSS under the div tag "card-body", ideally the width should match the width of my browser if im understanding this correctly?

**Comment by domoritz** [comment]
Not necessarily. The width is 100% of the parent. Please use the developer tools to isolate the issue. 

For example, make sure to set the width on the chart container itself, not some distant ancestor. 

I’m going to close the issue for now. Please add a full reproduction with a minimal example.
