### ISSUE TITLE
Use Vega-Embed

### ISSUE THREAD

**Issue by kanitw** [vega/react-vega#26]

**Comment by seanlaff** [comment]
I've been using vega embed to get the "actions" menu which has been very handy- however it's lead me to mostly re-implementing react-vega within my component. It'd be great to see these two projects married :)

**Comment by kristw** [comment]
@seanlaff Would it be possible to share that piece of code for reference? That may help the conversion happens faster.

**Comment by kanitw** [comment]
```
import vegaEmbed from 'vega-embed';


// TODO: change to use react-vega once it is migrated to the latest version of vega-embed
export class Vega extends React.PureComponent {
  constructor(props) {
    super(props);
  }
  componentDidMount() {
    const {spec, config} = this.props;
    vegaEmbed(this.refs.component, spec, {config});
  }
  componentDidUpdate() {
    const {spec, config} = this.props;
    vegaEmbed(this.refs.component, spec, {config});
  }

  render() {
    return <div ref="component" />;
  }
}
```

This is a hacky one that I use right now.  (See TODO lol)

**Comment by kristw** [comment]
mmm. you are also using deprecated way of defining `ref`.

**Comment by seanlaff** [comment]
When I say `however it's lead me to mostly re-implementing react-vega within my component` I mostly meant that I re-implemented all the `componentShouldUpdate` logic that react-vega already solves.
