### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by yuby** [vega/react-vega#260]
after update version i've got some error!

TypeScript error in /node_modules/react-vega/lib/types/index.d.ts(1,13):
'=' expected.  TS1005

  > 1 | import type { Result } from 'vega-embed';
      |             ^
    2 | /** Vega View object */
    3 | export declare type View = Result['view'];
    4 | export declare type PlainObject = {

any solution?

**Comment by domoritz** [comment]
Are you on the latest version of typescript?

**Comment by yuby** [comment]
thanks! it's working!

**Comment by EntilZha** [comment]
I ran into the same issue, so wanted to see what the solution ended up being. I am on typescript 3.7.2, is the solution then to upgrade to typescript 4.x?

**Comment by u-phoria** [comment]
Upgrading typescript to 4.x worked for me.
