### ISSUE TITLE
goldred color scheme does not work

### ISSUE THREAD

**Issue by vnosikov** [vega/react-vega#34]
Hello.

I'm using  a createClassFromSpec function. I describe a color scale there

`{
      name: 'out-bar-color',
      domain: { data: 'outcoming', field: 'id' },
      range: { scheme: 'reds' },
      type: 'ordinal',
},`

It works. But if I use "goldred" color scheme instead of "reds" I will get an empty image instead of a plot. I can use this scheme in vega online editor though. Do I understand correctly that some color schemes are not supported? Could you specify which ones and are there any plans to fix it.

Thank you

**Comment by domoritz** [comment]
Please file an issue against Vega or Vega-Lite unless this is react specific.
