### ISSUE TITLE
Broken package: replace lazynerd-devtools

### ISSUE THREAD

**Issue by domoritz** [vega/react-vega#35]
v5 does not work. The error is `Uncaught ReferenceError: regeneratorRuntime is not defined`.

**Comment by domoritz** [comment]
We should instead use https://github.com/developit/microbundle or just straight up rollup.

**Comment by siddhant1** [comment]
Will take a look at this after some time , but open for others to make the changes.

**Comment by kristw** [comment]
Let me see what I can do.

**Comment by kristw** [comment]
Done. Resolved and re-publish as `6.0.0`
