### ISSUE TITLE
does react-vega support any conditions?

### ISSUE THREAD

**Issue by XoBpawok** [vega/react-vega#365]
I know that it's wrapper only but idk why don't conditions work.
my case - is just change colot of bar chart on select type 'point'
it's like

` params: [
  {
    name: 'selected',
    select: { type: 'point' }
  }
]`
  and use it as
`
{
  mark: { type: 'bar', fill: 'green' },
  ...,
  fill: {
    condition: [
      {
        param: 'selected',
        empty: false,
        value: 'red'
      }
    ]
  }
}
`

**Comment by kanitw** [comment]
you use param which in VL 5's feature, so this depends on https://github.com/vega/react-vega/issues/367
