### ISSUE TITLE
Case sensitivity issues

### ISSUE THREAD

**Issue by kershnerd** [vega/react-vega#41]
On Windows, adding "react-vega": "^6.0.1", "vega": "^5.4.0" to the package.json file gives the following error when running storybook:

ERROR in ./node_modules/react-vega/esm/Vega.js
Module not found: Error: Cannot find file: 'vega.jsx' does not match the corresponding name on disk: '.\node_modules\react-vega\src\Vega.jsx'.
This works correctly with a create-create-app but not in storybook. My understanding is that case-sensitive-paths-webpack-plugin  is in both react-scripts and storybook, so not sure that is the issue.

And suggestions on how to fix this?

System:

OS: [Windows10]
Browser: [chrome]
Framework: [react]
Version: latest
Additional context
BTW.. there are no problems running on Ubuntu... this seems to be just a Windows issue. Also, not sure this relevant, but we are using yarn 1.16.0

**Comment by kershnerd** [comment]
Any suggestions on this or shall I just close it as an edge case?

**Comment by domoritz** [comment]
Are the file names correctly capitalized?

**Comment by kershnerd** [comment]
Not sure... package.json imports like this:
```
"react-vega": "^6.0.1",
"vega": "^5.4.0"
```

My component imports like this:
```
import Vega from "react-vega";
```

and I use it like this in a render method:
```
<Vega className={'text-center'} spec={spec} />
```

What else would I have to check?  This works correctly with webpack: `yarn start` but doesn't work with storybook: `yarn run storybook`.

Any ideas?

**Comment by domoritz** [comment]
I was wondering whether you could debug the react-vega code. I don't have a case sensitive file system so I cannot debug this but taking a brief look at the code, I can't see the problem. It would be great if you could help us fix this issue.

**Comment by kristw** [comment]
Does this issue still persist in the latest version?
