### ISSUE TITLE
Memory leak when using `onNewView`.

### ISSUE THREAD

**Issue by KhadijaMahanga** [vega/react-vega#436]
I am experiencing memory leak when using `onNewView`.

I think we should be calling `result.finalize()` [after this](https://github.com/vega/react-vega/blob/0b1aef3f572b88ddadac5e03336af49d4c22905c/packages/react-vega/src/VegaEmbed.tsx#L110) too. Just as how we finalized on clear view

**Comment by domoritz** [comment]
Why do you think we need to call finalize then? We may still use the view after calling this method, no?

**Comment by KhadijaMahanga** [comment]
@domoritz yes, you're right. Let me limit the calls, using hooks.
