### ISSUE TITLE
builds try to import a missing prop-types dependency

### ISSUE THREAD

**Issue by hukka** [vega/react-vega#441]
For some reason, even when it's not mentioned anywhere in the source code, the esm version needs prop-types (https://unpkg.com/react-vega@7.4.4/esm/Vega.js, first line) but it's missing from package.json dependencies. I guess quite often something else has an explicit dependency on prop-types so it ends up in node_modules anyway, but in very minimal projects this causes builds to fail.

I've never used nimbus which seems to be used for the esm builds, so no idea if that's a bug in build tools, or in the react-vega configs. Or in a dependency of react-vega (could it be @types/react)?

While I have been trying to use the esm version, a grep shows that also the builds in the lib do the same require.

**Comment by hukka** [comment]
Sure, if the manual addition to package.json is the way to handle it. That would be about the only way at the moment I know how to resolve it ;)

**Comment by aiba** [comment]
Also hit this issue.  Had to manually add "prop-types" and also "process" and "buffer" as dependencies.

**Comment by kristw** [comment]
@aiba Seems to caused by `babel-plugin-typescript-to-proptypes` that add `prop-types` during transpile time. Let me remove this.

**Comment by kristw** [comment]
Please try `react-vega@7.5.1`

**Comment by aiba** [comment]
With 7.5.1, still getting a missing dep on buffer, but perhaps this is a vega-loader issue?

```
logs/client-dev.log: The required JS dependency "buffer" is not available, it was required by "node_modules/vega-loader/build/vega-loader.browser.js".
logs/client-dev.log: Dependency Trace:
logs/client-dev.log: 	node_modules/react-vega/lib/index.js
logs/client-dev.log: 	node_modules/react-vega/lib/Vega.js
logs/client-dev.log: 	node_modules/react-vega/lib/utils/updateMultipleDatasetsInView.js
logs/client-dev.log: 	node_modules/react-vega/lib/utils/updateSingleDatasetInView.js
logs/client-dev.log: 	node_modules/vega-embed/build/vega-embed.js
logs/client-dev.log: 	node_modules/vega/build/vega-node.js
logs/client-dev.log: 	node_modules/vega-dataflow/build/vega-dataflow.js
logs/client-dev.log: 	node_modules/vega-loader/build/vega-loader.browser.js
```
