### ISSUE TITLE
Storybook doesn't rebuild when package sources change

### ISSUE THREAD

**Issue by domoritz** [vega/react-vega#46]
I make changes in react-vega or react-vega-lite but storybook doesn't reload.

**Comment by hungngo97** [comment]
Mine does change though, I changed some things on Vega.jsx, saved the file and it reloads

**Comment by domoritz** [comment]
On master? I have to try again then. Did you run some lerna command?

**Comment by domoritz** [comment]
Nope, doesn't work for me. Please post working instructions.

**Comment by hungngo97** [comment]
I did `yarn install && yarn build && yarn storybook` from a fresh new cloned repo

**Comment by domoritz** [comment]
And changes to the component source automatically trigger a rebuild? You don't have to run the command again?
