### ISSUE TITLE
Broken link to spec example in react-vega/packages/react-vega README

### ISSUE THREAD

**Issue by ccarterlandis** [vega/react-vega#51]
The provided spec example titled [BarChart.js](https://github.com/vega/react-vega/tree/master/packages/react-vega#barchartjs) contains a link to the rest of the spec, as the file was truncated for the sake of brevity. This link, however, leads [here](https://github.com/vega/react-vega/blob/master/packages/react-vega/demo/src/vega/spec1.js) - or (less?) more specifically, nowhere! I was also unable to locate the file manually, and the only file named `spec1.js` contains a spec for a table, and not for a BarChart.

**Comment by domoritz** [comment]
Should be https://github.com/vega/react-vega/blob/master/stories/vega/spec1.js, I guess

**Comment by kristw** [comment]
fixed.
