### ISSUE TITLE
Remove vega-lite stuff

### ISSUE THREAD

**Issue by domoritz** [vega/react-vega#55]
The Vega-Lite react component is deprecated.

* Remove https://github.com/vega/react-vega/tree/master/packages/react-vega-lite
* deprecate the npm package with https://docs.npmjs.com/cli/deprecate
* Update the storybook demo

**Comment by domoritz** [comment]
Does this make sense @kristw?

**Comment by kristw** [comment]
Already remove most of the code. Only left readme and old changelog in that dir.

**Comment by domoritz** [comment]
Cool, I see you also updated storybook. Shall we deprecate https://www.npmjs.com/package/react-vega-lite?

**Comment by kristw** [comment]
Just published `react-vega@7.0.0` and ran `npm deprecated react-vega-lite` a moment ago.
