### ISSUE TITLE
Fail with Layered Spec

### ISSUE THREAD

**Issue by eeyshen** [vega/react-vega#64]
React-vega does not work with vega or vega-lite json that consist of layer. Is there any method to do with that? Thanks.

**Comment by domoritz** [comment]
Could you provide an example that doesn't work?

**Comment by eeyshen** [comment]
Try this: https://vega.github.io/vega-lite/examples/wheat_wages.html.

**Comment by domoritz** [comment]
I made a simple layered spec and it worked. Please provide more details about what doesn't work. 

![Uploading Screen Shot 2019-10-15 at 11.03.33.png…]()

**Comment by eeyshen** [comment]
Do you try layer spec with multi datasets? I modify the vegalite demo in react-vega as follows, which do not work.

const data1 = {
  myData: [
    { a: "A", b: 20 },
    { a: "B", b: 34 },
    { a: "C", b: 55 },
    { a: "D", b: 19 },
    { a: "E", b: 40 },
    { a: "F", b: 34 },
    { a: "G", b: 91 },
    { a: "H", b: 78 },
    { a: "I", b: 25 }
  ]
};

const spec1 = {
  description: "A simple bar chart with embedded data.",
  layer: [
    {
      data: { name: "myData" },
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" }
      },
      mark: "bar"
    }
  ]
};

**Comment by domoritz** [comment]
What does not work?

**Comment by eeyshen** [comment]
I do not know. This is the result of spec as above.
<img width="479" alt="截屏2019-10-16上午9 32 16" src="https://user-images.githubusercontent.com/31716017/66881013-f6516200-eff7-11e9-92c6-b9c5e1ab64b5.png">

**Comment by eeyshen** [comment]
BTW. The following code works fine.
<img width="417" alt="截屏2019-10-16上午9 52 33" src="https://user-images.githubusercontent.com/31716017/66881816-b475eb00-effa-11e9-9a7f-b72b5b35cbe5.png">

**Comment by domoritz** [comment]
Can you give me a fully working example including the call to React-Vega?

**Comment by eeyshen** [comment]
Yes.  Based on the demo https://github.com/vega/react-vega/tree/master/packages/react-vega-demo/stories, I only change the 'spec1' in file ReactVegaLiteDemo.jsx to:

`const spec1 = {
  description: "A simple bar chart with embedded data.",
  layer: [
    {
      data: {
        name: "myData"
      },
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" }
      },
      mark: "bar"
    }
  ]
};`

It failed.

If I change spec1 to follow, it work fine.

`const spec1 = {
  description: "A simple bar chart with embedded data.",
  layer: [
    {
      data: {
        values: [
          { a: "A", b: 28 },
          { a: "B", b: 55 },
          { a: "C", b: 43 },
          { a: "D", b: 91 },
          { a: "E", b: 81 },
          { a: "F", b: 53 },
          { a: "G", b: 19 },
          { a: "H", b: 87 },
          { a: "I", b: 52 }
        ]
      },
      encoding: {
        x: { field: "a", type: "ordinal" },
        y: { field: "b", type: "quantitative" }
      },
      mark: "bar"
    }
  ]
};`

**Comment by domoritz** [comment]
The second example explicitly provides the data. Can you start debugging there? I don’t the the problem is layering.

**Comment by eeyshen** [comment]
I think the problem comes from that react-vega or vega-embed do not deal with input data correctly in layered chart. But I am not sure, and I do not know how to debug that.

**Comment by domoritz** [comment]
Vega-Embed definitely supports multiple datasets. @kristw could help with how we handle multiple datasets in react vega.

**Comment by kristw** [comment]
See #66

**Comment by eeyshen** [comment]
Great. Looking forward to the next release with this feature.
