### ISSUE TITLE
Do we need vega-tooltip to use Vega Tooltip?

### ISSUE THREAD

**Issue by eeyshen** [vega/react-vega#65]
As https://github.com/vega/react-vega/tree/master/packages/react-vega and https://www.npmjs.com/package/react-vega show that it needs vega-tooltip to display tooltip, but the demo does not use, while tooltip works fine.  It is confusing. Do we need vega-tooltip to use Vega Tooltip?

**Comment by domoritz** [comment]
Without Vega tooltip, you get native tooltips with html titles. With Vega tooltip, you get beautiful and instant html tooltips. 

Can you help us update the docs to make this clearer?

**Comment by eeyshen** [comment]
I tried both with the demo. The following two screenshots show react-vega without and with vega-tooltip separately. But I cannot find the difference. Is there mistake?

![react-vega](https://user-images.githubusercontent.com/31716017/66879827-a8862b00-eff2-11e9-9cdb-e007f87a9442.png)
![react-vega-tooltip](https://user-images.githubusercontent.com/31716017/66879829-ade37580-eff2-11e9-9fe9-455e3f1f79d4.png)

**Comment by domoritz** [comment]
They both use Vega tooltip.

**Comment by eeyshen** [comment]
Do you mean these codes are the same?
1. <VegaLite data={data} spec={spec} signalListeners={this.handlers} />
2. <VegaLite data={data} spec={spec} signalListeners={this.handlers} tooltip={new Handler().call} />

**Comment by domoritz** [comment]
Vega-Embed automatically adds Vega-Tooltip so yes, I believe these two are equivalent.
