### ISSUE TITLE
Specifying array in "data":[{...}]" results in Unrecognized data set?

### ISSUE THREAD

**Issue by cmdcolin** [vega/react-vega#74]
I was trying to use this component and created this demo

https://github.com/cmdcolin/cra_starter_pack/blob/master/src/App.js

It works fine with this spec

```
const spec = {
  description: 'A simple bar chart with embedded data.',
  data: { name: 'table' },
  mark: 'bar',
  encoding: {
    x: { field: 'a', type: 'ordinal' },
    y: { field: 'b', type: 'quantitative' },
  },
}
```

If I change it to data: [{name : 'table'}] like in https://github.com/vega/react-vega/tree/master/packages/react-vega#mainjs-1 it causes this

```
embed.js:88 The input spec uses Vega-Lite v4, but the current version of Vega-Lite is v4.0.0-beta.12.
guessMode @ embed.js:88
logger.js:3 WARN Infinite extent for field "b": [Infinity, -Infinity]
log @ logger.js:3
2VegaEmbed.js:48 Error: Unrecognized data set: table
    at error.js:2
    at dataref (data.js:7)
    at View.change (data.js:20)
    at updateData (Vega.js:49)
    at Vega.js:83
    at Array.forEach (<anonymous>)
    at Vega.js:82
    at VegaEmbed.js:51
```

Versions

```
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.2.0",
    "react-vega": "^7.1.1",
    "vega": "^5.8.1",
    "vega-lite": "^4.0.0-beta.12"
```

It is not a big concern because I am really only using one dataset so I don't need to array, but I was confused seeing this error

**Comment by domoritz** [comment]
`data: [{name : 'table'}]` only works in Vega. The spec above is Vega-Lite.

**Comment by cmdcolin** [comment]
If possible I might suggest maybe adding a comment about this in the readme now that react-vega-lite is deprecated?, or the error message even, or a schema validation error? It is just one of those things where I repeatedly saw this error message, and then I looked at the docs and nothing really helped me to figure it out.

I guess I was also confused because I tried just specifying data={{values: [...]}} in the VegaLite props without having "data": {"name": "values"} and that failed, so I had to manually add that to my schema (I thought maybe it would automatically infer it for some reason)

Just trying to give a user perspective...

**Comment by domoritz** [comment]
Could you send a pull request or file a separate issue that describes what you would like documented?

**Comment by cmdcolin** [comment]
Updated in #75 

Just some ideas :)
