### ISSUE TITLE
How to keep the scale not change?

### ISSUE THREAD

**Issue by ObservedObserver** [vega/react-vega#77]
case1: there are many chartView in one vega-lite chart, I want to use the selection, transform feature to implement a crossfilter. but the chart of which dataset is filtered may change its own scale (domain and range). It caused the chart size is keep changing and destroy the dashboard's layout.

case2: there are many independent vega-lite chart. when the dataSource is changing, I want to keep the domain and range not change to have a better observation of the changing of the data at a const scale. (it is also a little hard to figure out the stack interval's scale through the raw data becaused it is aggregated, is there any easy way to get the scale vega has complete after the chart is rendered and keep it const?)

**Comment by domoritz** [comment]
You can set the scale range and domain.
