### ISSUE TITLE
Resizing graph causes spec change each time the value changes.

### ISSUE THREAD

**Issue by snowl** [vega/react-vega#79]
Hi,

I'm trying out vega in my application as an alternative to other graphing libraries - I really like the idea of having a standard grammar that anyone can edit to create custom graphs.

One of the requirements in my application is that we allow the user to resize their graphs. I tried implementing this in react-vega and found two issues:

* (This one is minor) When passing in width/height into the Vega component, the width gets ignored but the height is listened to.

* Each time the value of the width/height changes, Vega re-renders the entire spec change but I haven't actually changed the data.

I can't see any real way of modifying the width/height without causing a spec change. I created a codepen which demonstrates the issue here: https://codesandbox.io/s/gallant-brook-0pbbn?fontsize=14&hidenavigation=1&theme=dark

The biggest issue is that this causes crazy amounts of lag, especially when your data source is large.

When looking at the Vega documentation (https://vega.github.io/vega-lite/docs/size.html), they have a demonstration of resizing a graph without any lag, under the heading "Specifying Responsive Width and Height". If you open up the example in the Vega Editor, you are able to resize the graph and it feels silky smooth, which is what I want.

Any help/advice on this would be great!

Cheers,
David

**Comment by kristw** [comment]
@snowl `react-vega` is currently doing a cheap comparison whether spec is changed. If change, it discard and  It may need to dig deeper into the spec to figure out if only size was changed. I'll flag this as feature request. 

> (This one is minor) When passing in width/height into the Vega component, the width gets ignored but the height is listened to.

Is the width numeric? Is the outcome width 100% of container instead?
