### ISSUE TITLE
Module not found - core-js-stable/array

### ISSUE THREAD

**Issue by CoryCasanave** [vega/react-vega#97]
Trying to load the example, a module was not found: 

Module not found: Can't resolve '@babel/runtime-corejs3/core-js-stable/array/from' in <dir>\Dev\JS\~\stardog-react\node_modules\react-vega\esm'

The import is: import  {Vega}  from 'react-vega';

Where as this works:
import Vega1 from 'vega';

Node JS version: 12.13.0

Perhaps a javascript version issue?
Any ideas?Thanks!

**Comment by nkrumm** [comment]
This same error is breaking my build as of today as well. I updated react-vega, vega and vega-lite, as well as regenerated my install and package-lock... no difference yet.

```
Module not found: Can't resolve '@babel/runtime-corejs3/core-js-stable/array/from' in '/Users/nkrumm/projects/INFRASTRUCTURE/batchman/frontend/node_modules/react-vega/esm'
```

Package.json:
```
{
  "name": "frontend",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@reach/router": "^1.2.1",
    "bootstrap": "^4.3.1",
    "date-fns": "^2.4.1",
    "http-proxy-middleware": "^0.20.0",
    "query-string": "6.9.0",
    "react": "^16.10.2",
    "react-ace": "^8.0.0",
    "react-bootstrap": "^1.0.0-beta.14",
    "react-bootstrap-table-next": "^3.2.1",
    "react-bootstrap-typeahead": "^3.4.7",
    "react-dom": "^16.10.2",
    "react-dropzone": "^10.2.1",
    "react-fetching-library": "^1.5.12",
    "react-icons": "^3.7.0",
    "react-jsonschema-form": "^1.8.1",
    "react-scripts": "3.2.0",
    "react-string-replace": "^0.4.4",
    "react-syntax-highlighter": "^11.0.2",
    "react-vega": "^7.2.0",
    "svgo": "1.3.0",
    "use-clipboard-copy": "^0.1.1",
    "vega": "^5.9.1",
    "vega-lite": "^4.1.1"
  },
  "resolutions": {
    "svgo": "1.3.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

Node.js v12.10.0 and npm 6.11.3

**Comment by onetonfoot** [comment]
I just had the same error, I fixed it by running
```
npm install --save-dev @babel/runtime-corejs3
```

**Comment by CoryCasanave** [comment]
@onetonfoot  - that worked, thanks!

**Comment by kristw** [comment]
Sorry for the issue. 
Just remove one babel transform and publish the patch in `7.2.1`. Please let me know if that helps.

**Comment by LauraGlt** [comment]
Using react-vega 7.2.1 and stil having this error : 
`Module not found: Can't resolve 'core-js/modules/es.array.concat' in '/Users/front/node_modules/react-vega/esm'`

Any idea?

**Comment by kristw** [comment]
npm install core-js —save

I will add this to dependency in the next release

**Comment by MUHAMMADDIN786** [comment]
> I just had the same error, I fixed it by running
> 
> ```
> npm install --save-dev @babel/runtime-corejs3
> ```

ys this worked,, thanks
